# Generated by Django 6.1.1 on 2026-09-29 06:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id_usuario', models.BigAutoField(db_column='id_usuario', primary_key=True, serialize=False)),
                ('nm_usuario', models.CharField(db_column='nm_usuario', max_length=100)),
                ('email_usuario', models.EmailField(db_column='email_usuario', max_length=254, unique=True)),
                ('tel_usuario', models.CharField(blank=True, db_column='tel_usuario', max_length=20, null=True)),
                ('cpf_cnpj_usuario', models.CharField(blank=True, db_column='cpf_cnpj_usuario', max_length=20, null=True, unique=True)),
                ('cargo_usuario', models.CharField(choices=[('CLIENTE', 'Cliente'), ('ADMIN', 'Administrador')], db_column='cargo_usuario', max_length=20)),
                ('usuario_ativo', models.BooleanField(db_column='usuario_ativo', default=True)),
                ('dt_criacao', models.DateTimeField(auto_now_add=True, db_column='dt_criacao')),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id_endereco', models.BigAutoField(db_column='id_endereco', primary_key=True, serialize=False)),
                ('endereco_principal', models.BooleanField(db_column='endereco_principal')),
                ('cep_endereco', models.CharField(db_column='cep_endereco', max_length=10)),
                ('logr_endereco', models.CharField(db_column='logr_endereco', max_length=150)),
                ('num_endereco', models.CharField(db_column='num_endereco', max_length=20)),
                ('complemento_endereco', models.CharField(blank=True, db_column='complemento_endereco', max_length=50, null=True)),
                ('bairro_endereco', models.CharField(db_column='bairro_endereco', max_length=50)),
                ('cidade_endereco', models.CharField(db_column='cidade_endereco', max_length=50)),
                ('estado', models.CharField(db_column='estado', max_length=2)),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='enderecos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'endereco',
            },
        ),
    ]
