# Generated by Django 6.1.1 on 2026-09-29 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.BigAutoField(db_column='id_categoria', primary_key=True, serialize=False)),
                ('nm_categoria', models.CharField(db_column='nm_categoria', max_length=50, unique=True)),
            ],
            options={
                'db_table': 'categoria',
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id_produto', models.BigAutoField(db_column='id_produto', primary_key=True, serialize=False)),
                ('nm_produto', models.CharField(db_column='nm_produto', max_length=100)),
                ('ds_produto', models.TextField(blank=True, db_column='ds_produto', null=True)),
                ('tipo_pele_produto', models.CharField(blank=True, db_column='tipo_pele_produto', max_length=50, null=True)),
                ('produto_ativo', models.BooleanField(db_column='produto_ativo', default=True)),
                ('dt_criacao', models.DateTimeField(auto_now_add=True, db_column='dt_criacao')),
            ],
            options={
                'db_table': 'produto',
            },
        ),
        migrations.CreateModel(
            name='ProdutoCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_categoria', models.ForeignKey(db_column='id_categoria', on_delete=django.db.models.deletion.CASCADE, to='catalog.categoria')),
                ('id_produto', models.ForeignKey(db_column='id_produto', on_delete=django.db.models.deletion.CASCADE, to='catalog.produto')),
            ],
            options={
                'db_table': 'produto_categoria',
                'unique_together': {('id_produto', 'id_categoria')},
            },
        ),
        migrations.AddField(
            model_name='produto',
            name='categorias',
            field=models.ManyToManyField(related_name='produtos', through='catalog.ProdutoCategoria', to='catalog.categoria'),
        ),
        migrations.CreateModel(
            name='ProdutoVariacao',
            fields=[
                ('id_variacao', models.BigAutoField(db_column='id_variacao', primary_key=True, serialize=False)),
                ('sku_produto', models.CharField(db_column='sku_produto', max_length=50, unique=True)),
                ('nm_variacao', models.CharField(db_column='nm_variacao', max_length=50)),
                ('vl_produto', models.DecimalField(db_column='vl_produto', decimal_places=2, max_digits=10)),
                ('vl_promo_produto', models.DecimalField(blank=True, db_column='vl_promo_produto', decimal_places=2, max_digits=10, null=True)),
                ('dt_inicio_promo_produto', models.DateTimeField(blank=True, db_column='dt_inicio_promo_produto', null=True)),
                ('dt_fim_promo_produto', models.DateTimeField(blank=True, db_column='dt_fim_promo_produto', null=True)),
                ('peso_gramas_produto', models.IntegerField(blank=True, db_column='peso_gramas_produto', null=True)),
                ('qtd_estoque_produto', models.IntegerField(db_column='qtd_estoque_produto')),
                ('id_produto', models.ForeignKey(db_column='id_produto', on_delete=django.db.models.deletion.CASCADE, related_name='variacoes', to='catalog.produto')),
            ],
            options={
                'db_table': 'produto_variacao',
                'unique_together': {('id_produto', 'nm_variacao')},
            },
        ),
    ]
