# Generated by Django 6.1.1 on 2026-09-29 06:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido', models.BigAutoField(db_column='id_pedido', primary_key=True, serialize=False)),
                ('entrega_cep', models.CharField(db_column='entrega_cep', max_length=10)),
                ('entrega_logradouro', models.CharField(db_column='entrega_logradouro', max_length=150)),
                ('entrega_numero', models.CharField(db_column='entrega_numero', max_length=20)),
                ('entrega_complemento', models.CharField(blank=True, db_column='entrega_complemento', max_length=50, null=True)),
                ('entrega_bairro', models.CharField(db_column='entrega_bairro', max_length=50)),
                ('entrega_cidade', models.CharField(db_column='entrega_cidade', max_length=50)),
                ('entrega_estado', models.CharField(db_column='entrega_estado', max_length=2)),
                ('status_pedido', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGO', 'Pago'), ('ENVIADO', 'Enviado'), ('ENTREGUE', 'Entregue'), ('CANCELADO', 'Cancelado')], db_column='status_pedido', default='PENDENTE', max_length=30)),
                ('vl_total_pedido', models.DecimalField(db_column='vl_total_pedido', decimal_places=2, max_digits=10)),
                ('vl_frete_pedido', models.DecimalField(db_column='vl_frete_pedido', decimal_places=2, max_digits=10)),
                ('dt_criacao', models.DateTimeField(auto_now_add=True, db_column='dt_criacao')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pedido',
            },
        ),
        migrations.CreateModel(
            name='PedidoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(db_column='quantidade')),
                ('preco', models.DecimalField(db_column='preco', decimal_places=2, max_digits=10)),
                ('id_pedido', models.ForeignKey(db_column='id_pedido', on_delete=django.db.models.deletion.CASCADE, to='orders.pedido')),
                ('id_variacao', models.ForeignKey(db_column='id_variacao', on_delete=django.db.models.deletion.PROTECT, to='catalog.produtovariacao')),
            ],
            options={
                'db_table': 'pedido_item',
                'unique_together': {('id_pedido', 'id_variacao')},
            },
        ),
        migrations.AddField(
            model_name='pedido',
            name='itens',
            field=models.ManyToManyField(related_name='pedidos', through='orders.PedidoItem', to='catalog.produtovariacao'),
        ),
    ]
