# Generated by Django 6.1.1 on 2026-09-29 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MateriaPrima',
            fields=[
                ('id_materia_prima', models.BigAutoField(db_column='id_materia_prima', primary_key=True, serialize=False)),
                ('nm_materia_prima', models.CharField(db_column='nm_materia_prima', max_length=100, unique=True)),
                ('unidade_medida', models.CharField(db_column='unidade_medida', max_length=10)),
                ('qtd_estoque', models.DecimalField(db_column='qtd_estoque', decimal_places=3, max_digits=10)),
                ('custo_unitario', models.DecimalField(db_column='custo_unitario', decimal_places=4, max_digits=10)),
            ],
            options={
                'db_table': 'materia_prima',
            },
        ),
        migrations.CreateModel(
            name='MovimentacaoEstoque',
            fields=[
                ('id_movimentacao', models.BigAutoField(db_column='id_movimentacao', primary_key=True, serialize=False)),
                ('tipo_movimentacao', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA_VENDA', 'Saída por Venda'), ('AJUSTE_PERDA', 'Ajuste / Perda')], db_column='tipo_movimentacao', max_length=20)),
                ('qtd_movimentacao', models.IntegerField(db_column='qtd_movimentacao')),
                ('ds_observacao', models.TextField(blank=True, db_column='ds_observacao', null=True)),
                ('dt_movimentacao', models.DateTimeField(auto_now_add=True, db_column='dt_movimentacao')),
                ('id_variacao', models.ForeignKey(db_column='id_variacao', on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='catalog.produtovariacao')),
            ],
            options={
                'db_table': 'movimentacao_estoque',
            },
        ),
        migrations.CreateModel(
            name='FichaTecnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtd_necessaria', models.DecimalField(db_column='qtd_necessaria', decimal_places=3, max_digits=10)),
                ('id_variacao', models.ForeignKey(db_column='id_variacao', on_delete=django.db.models.deletion.CASCADE, related_name='fichas_tecnicas', to='catalog.produtovariacao')),
                ('id_materia_prima', models.ForeignKey(db_column='id_materia_prima', on_delete=django.db.models.deletion.RESTRICT, related_name='fichas_tecnicas', to='inventory.materiaprima')),
            ],
            options={
                'db_table': 'ficha_tecnica',
                'unique_together': {('id_variacao', 'id_materia_prima')},
            },
        ),
    ]
